config/routes.rb
Rails.application.routes.draw do


  devise_for :users



  resources :heroe_sets, only: [:index]

  get 'store', to: 'heroe_sets#index'

  #recursos anidados
  resources :heroes do
    resources :abilities
    resources :heroe_sets
  end

  get 'heroes/index'

  root "heroes#index"




end

app/models/heroe_set.rb
class HeroeSet < ActiveRecord::Base
  belongs_to :heroe

  validates :title, presence:true, length: { minimum: 5}
  validates :description, presence:true , length: { minimum: 10}
  validates :heroe, presence:true
  validates :rarity, presence:true, length: { minimum: 3}
  validates :active, presence:true
  validates :cost, presence:true

end

app/controllers/heroe_sets_controller.rb
class HeroeSetsController < ApplicationController
  before_action :set_heroe_set, only: [:show, :edit, :update, :destroy]
  before_action :set_heroe , only: [:show, :edit, :update, :destroy]


  # GET /heroe_sets
  # GET /heroe_sets.json
  def index
    @heroe_sets = HeroeSet.all()
    #@heroe_sets = HeroeSet.all
  end

  # GET /heroe_sets/1
  # GET /heroe_sets/1.json
  def show
  end

  # GET /heroe_sets/new
  def new
    @heroe_set = HeroeSet.new()
    @heroe_set.heroe = @heroe
  end

  # GET /heroe_sets/1/edit
  def edit
  end

  # POST /heroe_sets
  # POST /heroe_sets.json
  def create
    @heroe_set = HeroeSet.new(heroe_set_params)

    respond_to do |format|
      if @heroe_set.save
        format.html { redirect_to @heroe_set, notice: 'Heroe set was successfully created.' }
        format.json { render :show, status: :created, location: @heroe_set }
      else
        format.html { render :new }
        format.json { render json: @heroe_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heroe_sets/1
  # PATCH/PUT /heroe_sets/1.json
  def update
    respond_to do |format|
      if @heroe_set.update(heroe_set_params)
        format.html { redirect_to @heroe_set, notice: 'Heroe set was successfully updated.' }
        format.json { render :show, status: :ok, location: @heroe_set }
      else
        format.html { render :edit }
        format.json { render json: @heroe_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heroe_sets/1
  # DELETE /heroe_sets/1.json
  def destroy
    @heroe_set.destroy
    respond_to do |format|
      format.html { redirect_to heroe_sets_url, notice: 'Heroe set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_heroe
      @heroe = Heroe.find(params[:hero_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_heroe_set
      @heroe_set = HeroeSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def heroe_set_params
      params.require(:heroe_set).permit(:title, :description, :active, :heroe_id, :cost)
    end
end

app/helpers/heroe_sets_helper.rb
module HeroeSetsHelper
end

app/views/heroe_sets/_form.html.erb
<div ng-app="appEditForm">


  <div ng-controller="mainController">
    <%= form_for([@heroe,@heroe_set]) do |f| %>
  <% if @heroe_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@heroe_set.errors.count, "error") %> prohibited this heroe_set from being saved:</h2>

      <ul>
      <% @heroe_set.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :rarity %><br>
    <%= f.text_field :rarity %>
  </div>


  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :heroe_id %><br>
    <%= f.text_field :heroe_id %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<h1>Welcome</h2>
<div ng-controller="mainController">
  <label>Single Upload</label>
  <input type="file" ng-file-select="onFileSelect($files)"/><br/>
  <label>Multiple Upload</label>
  <input type="file" ng-file-select="onFileSelect($files)" multiple accept="image/*"/>

  <div ng-file-drop-available="dropSupported=true" ng-show="!dropSupported"> Drop file not supported </div>
</div>


  </div>
</div>

<script type="text/javascript">

  angular.module("appEditForm",["ngResource", "ng-rails-csrf","angularFileUpload"])

  .factory("Heroes",function($resource){

     return $resource("/heroes/<%= @heroe.id %>/abilities.json", {},{
       get: { method: 'GET'},
       create: { method: 'POST',url :"/heroes/<%= @heroe.id %>/abilities"},
       delete: { method: 'DELETE',url :"/heroes/<%= @heroe.id %>/abilities/:id", params: {id: '@id'}},
       update: { method: 'PUT',url :"/heroes/<%= @heroe.id %>/abilities/:id", params: {id: '@id'}}

     })
  })

  .controller("mainController", function($scope, FileUploader){


      $scope.onFileSelect = function($files){
        for (var i =0; i<$files.length; i++){
          var file = $files[i];

          $scope.upload = $upload.upload({
            url:'images/',
            data: {},
            file: file
          }).success(function(){
            alert("finished!");
          });
        };
      };
});


</script>

app/views/heroe_sets/edit.html.erb
<h1>Editing Heroe Set</h1>

<%= render 'form' %>

<%= link_to 'Show', @heroe_set %> |
<%= link_to 'Back', heroe_sets_path %>

app/views/heroe_sets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Active</th>
      <th>Heroe</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @heroe_sets.each do |heroe_set| %>
      <tr>
        <td><%= heroe_set.title %></td>
        <td><%= heroe_set.description %></td>
        <td><%= heroe_set.active %></td>
        <td><%= heroe_set.heroe %></td>
        <td><%= heroe_set.cost %></td>
        <td><%= link_to 'Show', heroe_set %></td>
        <td><%= link_to 'Edit', edit_heroe_set_path(heroe_set) %></td>
        <td><%= link_to 'Destroy', heroe_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/heroe_sets/new.html.erb
<h1>New Heroe Set</h1>

<%= render 'form' %>

<%= link_to 'Back', hero_heroe_sets_path([@heroe])   %>

app/views/heroe_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @heroe_set.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @heroe_set.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @heroe_set.active %>
</p>

<p>
  <strong>Heroe:</strong>
  <%= @heroe_set.heroe %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @heroe_set.cost %>
</p>

<%= link_to 'Edit', edit_heroe_set_path(@heroe_set) %> |
<%= link_to 'Back', heroe_sets_path %>