config/routes.rb
Rails.application.routes.draw do


  devise_for :users



  resources :heroe_sets, only: [:index]

  get 'store', to: 'heroe_sets#index'

  #recursos anidados
  resources :heroes do
    resources :abilities
    resources :heroe_sets
  end

  get 'heroes/index'

  root "heroes#index"




end

app/models/heroe.rb
class Heroe < ActiveRecord::Base
  belongs_to :heroeattribute
  has_many :ability
  has_many :heroe_set
  has_many :attachment_set

  validates :name, presence:true, uniqueness: true
  validates :description, presence:true , length: { minimum: 20}

  validates :heroeattribute, presence: true

  has_attached_file :image,
            :path => ":rails_root/public/system/:attachment/heroe/:style/:filename",
            :url => "/system/:attachment/heroe/:style/:filename",
            styles: { medium: "300x300", thumb:"256x144", mini:"59x33" }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/heroes_controller.rb
class HeroesController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]
  before_action :set_heroeattribute, only: [:create, :update]

  before_action :authenticate_user!, except: [:index, :show]

  # GET /heroes
  # GET /heroes.json
  def index
    @heroes = Heroe.all
  end

  # GET /heroes/1
  # GET /heroes/1.json
  def show
  end

  # GET /heroes/new
  def new
    @heroe = Heroe.new
  end

  # GET /heroes/1/edit
  def edit
    @ability = Ability.new
  end

  # POST /heroes
  # POST /heroes.json
  def create
    @heroe = Heroe.new(hero_params)
    @heroe.heroeattribute =  @heroeattribute

    respond_to do |format|
      if @heroe.save
        format.html { redirect_to @heroe, notice: 'Heroe was successfully created.' }
        format.json { render :show, status: :created, location: @heroe }
      else
        format.html { render :new }
        format.json { render json: @heroe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heroes/1
  # PATCH/PUT /heroes/1.json
  def update
    respond_to do |format|
      if @heroe.update(hero_params)
        format.html { redirect_to @heroe, notice: 'Heroe was successfully updated.' }
        format.json { render :show, status: :ok, location: @heroe }
      else
        format.html { render :edit }
        format.json { render json: @heroe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heroes/1
  # DELETE /heroes/1.json
  def destroy
    @heroe.destroy
    respond_to do |format|
      format.html { redirect_to heroes_url, notice: 'Heroe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @heroe = Heroe.find(params[:id])
    end

    def set_heroeattribute
      @heroeattribute = Heroeattribute.find(params[:heroe][:heroeattribute_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hero_params
      params.require(:heroe).permit(:name, :description , :video, :heroeattribute_id, :image)
    end
end

app/helpers/heroes_helper.rb
module HeroesHelper
end

app/views/heroes/_form.html.erb
<%= form_for(@heroe) do |f| %>
  <% if @heroe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@heroe.errors.count, "error") %> prohibited this hero from being saved:</h2>

      <ul>
      <% @heroe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>

    <% if !@heroe.image.nil? %>
      <%= image_tag @heroe.image.url(:medium) %>
    <% end %>



  </div>
  <div class="field">
    <%= f.label :heroeattributes_id %><br>

    <%= f.select :heroeattribute_id, Heroeattribute.all.collect {|c| [c.name, c.id] } , {prompt: 'Selecciona un Atributo'} %>


  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/heroes/edit.html.erb
<br>
<nav class="navbar navbar-inverse">

<div class="row">

<div class="row">
  <div class="col-md-3 col-md-offset-5">
      <h1 style="color:#fff"><%= @heroe.name %></h1>
  </div>
</div>


  <div class="col-md-4 col-md-offset-4">

  </div>
</div>

</nav>


<div class="row" ng-app="appEditForm">

  <div class="col-md-12">

    <div class="bs-example bs-example-tabs" data-example-id="togglable-tabs">

        <ul id="myTabs" class="nav nav-tabs" role="tablist">

          <li role="presentation" class="active">
            <a href="#info" id="info-tab" role="tab" data-toggle="tab" aria-controls="info" aria-expanded="true">Informacion General</a>
          </li>

          <li role="presentation" class="">
            <a href="#habilidad" role="tab" id="habilidad-tab" data-toggle="tab" aria-controls="habilidad" aria-expanded="false">Habilidades</a>
          </li>

          <li role="presentation" class="">
            <a href="#sets" role="tab" id="sets-tab" data-toggle="tab" aria-controls="sets" aria-expanded="false">Sets</a>
          </li>

        </ul>

        <div id="myTabContent" class="tab-content">

          <div role="tabpanel" class="tab-pane fade active in" id="info" aria-labelledby="info-tab">
            <%= render 'form' %>
          </div>

          <div role="tabpanel" class="tab-pane fade" id="habilidad" aria-labelledby="habilidad-tab" ng-controller="habilidadesCtrl">

              <div class="row">

                <div class="col-md-8">
                    <%= render 'abilities/lista' %>
                </div>

                <div class="col-md-4">
                    <%= render 'abilities/form' %>
                </div>

              </div>

          </div>

          <div role="tabpanel" class="tab-pane fade" id="sets" aria-labelledby="sets-tab">

          </div>

    </div>
  </div>


  </div>
</div>


<script type="text/javascript">



angular.module("appEditForm",["ngResource", "ng-rails-csrf","angularFileUpload"])

  .factory("Heroes",function($resource){

     return $resource("/heroes/<%= @heroe.id %>/abilities.json", {},{
       get: { method: 'GET'},
       create: { method: 'POST',url :"/heroes/<%= @heroe.id %>/abilities"},
       delete: { method: 'DELETE',url :"/heroes/<%= @heroe.id %>/abilities/:id", params: {id: '@id'}},
       update: { method: 'PUT',url :"/heroes/<%= @heroe.id %>/abilities/:id", params: {id: '@id'}}

     })
  })

  .controller("habilidadesCtrl",function($scope,Heroes, FileUploader){

      $scope.reset = function(){

          $scope.habilidades  = {};
          $scope.skill        = {};
          $scope.errors       = [];
          $scope.habilidades  = Heroes.get();
          $scope.edit   = false;

      }


      $scope.edit   = false;
      $scope.url = "/heroes/<%= @heroe.id %>/abilities";
      $scope.reset();


      var upload  = $scope.uploader = new FileUploader({

            url: $scope.url,
            formData:[],
            removeAfterUpload: true,
            onBeforeUploadItem: function (item){


            $scope.url = ( $scope.edit  ) ? "/heroes/<%= @heroe.id %>/abilities/$scope.skill.id": $scope.url;

              item.formData.push({ name:$scope.skill.name ,
                                     description :$scope.skill.description,
                                     authenticity_token :"<%= form_authenticity_token  %>"
                                });
            },
            onSuccessItem: function (item,response,status,headers){

                $scope.reset();


            }


        });

      $scope.cleanUpload = function (){

        upload.clearQueue();
      }


      $scope.editForm= function(habilidad){

        $scope.edit   = true;

        $scope.skill = {

            name : habilidad.name,
            id : habilidad.id,
            description : habilidad.description,
            image :habilidad.image_url
        };

      }

      $scope.Eliminar= function(habilidad){

         $scope.edit   = false;

          Heroes.delete({id: habilidad.id}, function(data){

              if( data.success ){
                alert(data.success);
              }else{
                alert(errors);
              }

              $scope.reset();

          }, function(error){
            $scope.errors.push(error.data.errors);
            $scope.reset();
          });

      }

      $scope.Edit= function(habilidad){

         $scope.edit   = false;

          Heroes.update({ name : habilidad.name,
                          id : habilidad.id,
                          description : habilidad.description,

             }, function(data){

              $scope.reset();

          }, function(error){
            $scope.errors.push(error.data.errors);
            $scope.reset();
          });

      }



  });



</script>

app/views/heroes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

  <% @heroes.each do |hero| %>

    <div class="col-xs-2 col-md-2">

        <% if user_signed_in? %>
            <%=link_to( image_tag(hero.image.url(:medium)), edit_hero_path(hero), :class=>"thumbnail") %>
        <% else %>

            <%=link_to( image_tag(hero.image.url(:medium)), hero_path(hero), :class=>"thumbnail") %>
        <% end %>

    </div>

  <% end %>

</div>


<br>

    <% if user_signed_in? %>
        <%= link_to 'New Heroe', new_hero_path, :class=>"btn btn-success" %>
    <% end %>

app/views/heroes/new.html.erb
<h1>New Hero</h1>

<%= render 'form' %>

<%= link_to 'Back', heroes_path %>

app/views/heroes/show.html.erb
<br>
<br>
<ul id="myTabs" class="nav nav-tabs" role="tablist"> <li role="presentation" class="active"><a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Home</a></li> <li role="presentation" class=""><a href="#profile" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile" aria-expanded="false">Profile</a></li> <li role="presentation" class="dropdown"> <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown" aria-controls="myTabDrop1-contents" aria-expanded="false">Dropdown <span class="caret"></span></a> <ul class="dropdown-menu" aria-labelledby="myTabDrop1" id="myTabDrop1-contents"> <li class=""><a href="#dropdown1" role="tab" id="dropdown1-tab" data-toggle="tab" aria-controls="dropdown1" aria-expanded="false">@fat</a></li> <li class=""><a href="#dropdown2" role="tab" id="dropdown2-tab" data-toggle="tab" aria-controls="dropdown2" aria-expanded="false">@mdo</a></li> </ul> </li> </ul>


<div class="row">


  <div class="col-md-8">

    <p id="notice"><%= notice %></p>


    <p>
      <strong>Description:</strong>
      <%= @heroe.description %>
    </p>

    <% @heroe.ability.each do |ab| %>
    <div class="panel panel-default">
      <div class="panel-heading"><%= ab.name %></div>
      <div class="panel-body">

        <div class="media">
          <div class="media-left">

              <%= image_tag ab.image.url(:mini), class:"media-object"  %>

          </div>
          <div class="media-body">
            <p><%= ab.description %></p>
          </div>
        </div>

      </div>
    </div>
    <% end %>

  </div>

  <div class="col-md-4">

    <div class="panel panel-default">
      <div class="panel-heading"><%= @heroe.name %></div>
      <div class="panel-body">

        <div class="media">
          <div class="media-left">
               <%= image_tag @heroe.image.url(:medium) %>
          </div>

        </div>

      </div>
    </div>

  </div>

</div>